controller_list:
  - name: fake_right_hand_controller
    joints:
      - rh_WRJ2
      - rh_WRJ1
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_LFJ5
      - rh_LFJ4
      - rh_LFJ3
      - rh_LFJ2
      - rh_LFJ1
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
  - name: fake_left_hand_controller
    joints:
      - lh_WRJ2
      - lh_WRJ1
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1

  - name: fake_rh_first_finger_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
  - name: fake_rh_middle_finger_controller
    joints:
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
  - name: fake_rh_ring_finger_controller
    joints:
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
  - name: fake_rh_little_finger_controller
    joints:
      - rh_LFJ5
      - rh_LFJ4
      - rh_LFJ3
      - rh_LFJ2
      - rh_LFJ1
  - name: fake_rh_thumb_controller
    joints:
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_fingertips_controller
    joints:
      []
  - name: fake_rh_fingers_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_LFJ5
      - rh_LFJ4
      - rh_LFJ3
      - rh_LFJ2
      - rh_LFJ1
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_first_finger_thumb_controller
    joints:
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_middle_finger_thumb_controller
    joints:
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_ring_finger_thumb_controller
    joints:
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
  - name: fake_rh_little_finger_thumb_controller
    joints:
      - rh_LFJ5
      - rh_LFJ4
      - rh_LFJ3
      - rh_LFJ2
      - rh_LFJ1
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1


  - name: fake_lh_first_finger_controller
    joints:
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
  - name: fake_lh_middle_finger_controller
    joints:
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
  - name: fake_lh_ring_finger_controller
    joints:
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
  - name: fake_lh_little_finger_controller
    joints:
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
  - name: fake_lh_thumb_controller
    joints:
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_lh_fingertips_controller
    joints:
      []
  - name: fake_lh_fingers_controller
    joints:
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_lh_first_finger_thumb_controller
    joints:
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_lh_middle_finger_thumb_controller
    joints:
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_lh_ring_finger_thumb_controller
    joints:
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_lh_little_finger_thumb_controller
    joints:
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
