right_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.05
  solve_type: Distance
right_arm_and_wrist:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
right_arm_and_manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
rh_first_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_fftip
rh_middle_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_mftip
rh_ring_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_rftip
rh_little_finger:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_lftip
rh_thumb:
  epsilon: 0.001
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_thtip
