#manipulator:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
manipulator:
  kinematics_solver: ur10srh_right_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_timeout: 0.05
  solve_type: Distance