robot:
  name: sr
  manipulators:
    right_manipulator:
      side: right
      hand:
        name: shadowhand_motor.urdf.xacro
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
    left_manipulator:
      side: left
      hand:
        name: shadowhand_left_motor.urdf.xacro
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
