robot:
  name: ur10srh
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10
        main_group: manipulator
        moveit_path: 
          package: sr_multi_moveit_config
          relative_path: /config/ur10
        group_states:
          - home
          - up
        kinematic_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
      hand:
        name: shadowhand_motor.urdf.xacro
