robot:
  name: sr
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10
        main_group: arm
        moveit_path: 
          package: sr_multi_moveit_config
          relative_path: /config/ur10
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
      hand:
        name: shadowhand_motor.urdf.xacro
