la_sr_ur_robot_hw:
  type: ur_driver/HardwareInterface
  
  # ra for right side arm la for left side arm
  robot_id: la
  
  # for sending robot programs
  robot_ip: 192.168.2.1
  
  # for the server that moves the robot 
  control_pc_ip_address: 192.168.2.100
    
  input_recipe_file: /home/user/projects/shadow_robot/base/src/Universal_Robots_ROS_Driver/ur_robot_driver/resources/rtde_input_recipe.txt
  
  output_recipe_file: /home/user/projects/shadow_robot/base/src/Universal_Robots_ROS_Driver/ur_robot_driver/resources/rtde_output_recipe.txt
  
  script_file: /home/user/projects/shadow_robot/base/src/Universal_Robots_ROS_Driver/ur_robot_driver/resources/servoj.urscript
  
  use_tool_communication: false
  
  headless_mode: false 
  
  servoj_gain: 300
  
  servoj_lookahead_time: 0.1

