robot:
  name: sr
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10
        main_group: right_arm
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
