robot:
  name: sr
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10
        main_group: right_arm
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
      hand:
        name: shadowhand_motor.urdf.xacro
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
    left_manipulator:
      side: left
      arm:
        name: ur10
        main_group: left_arm
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
      hand:
        name: shadowhand_left_motor.urdf.xacro
        group_states:
          - hold_bottle
          - approach_bottle
          - pour_bottle
          - victory
          - gamma
